export const satanDialogs = [
    "Welcome to Hell bitch. What, expecting someone taller? Too bad. Everything here costs 2HP. Walk up and hover on a relic to see what it does. Some help you, some curse you. That’s the game.",
    "No, I don’t make people do bad things. I just watch. Like Netflix, but meaner.",
    "I once tried therapy. My therapist burst into flames. Classic overreaction.",
    "You think you had a bad childhood? Try being blamed for everything since time began.",
    "I didn’t even have to tempt you. I just left the door unlocked and watched you sprint through it.",
    "You humans invented guilt by the way, that was even beyond what I could think of.",
    "Technically I’m middle management. The real evil? HR.",
    "God writes parables. I write punchlines.",
    "This isn’t even the worst level. The truly awful people are trapped in a group chat that never ends.",
    "Your ex is doing fine, by the way. Thanks for asking. She’s upstairs.",
    "You thought this was the bottom? Oh honey, we haven’t even started the orientation.",
    "You don’t need my help to destroy yourself. I’m just here for the encore.",
    "Oh no, don’t beat yourself up—I mean, you already outsourced that to me.",
    "Relax, you weren’t a monster. Monsters have goals. You were just… ambient damage.",
    "Ah yes, the classic ‘it’s complicated’ defense—because God forbid you just say ‘I’m selfish.’",
    "You didn’t destroy your family. You just ran the ‘emotionally distant husband’ speedrun and nailed every split.",
    "You said, ‘It’s not that simple.’ Buddy, it was. You just didn’t like the answer.",
    "You were ‘doing your best’? Cool. Did your best know it was ghosting your kid?",
    "You left because you were afraid you’d mess him up. Plot twist: You did it anyway. From a distance.",
    "You know what your real addiction was? Avoiding accountability. Whiskey was just the garnish.",
    "She didn’t leave because she stopped loving you. She left because loving you was like bailing water out of a sinking ship with a pasta strainer.",
    "You didn’t fail because you were broken. You failed because breaking things felt easier than fixing yourself.",
    "Your son’s first word was ‘Dada.’ His second was ‘where?’",
    "You didn’t hit rock bottom. You hit a mattress labeled ‘good enough’ and took a nap for ten years.",
    
];
