const drunkThoughts = [
    "I should text my ex",
    "Dad's the drunk",
    "Lost again",
    "not me",
    "Not drunk, thinking straight",
    "I can drive fine",
    "I'm good, not him",
    "Stop for gas... sleep",
    "Lights too bright, man",
    "Did I pass exit?",
    "Who put cars here?",
    "Lane's way too bendy",
    "Cars are so lazy",
    "Why cars so slow?",
    "Where'd the road go?",
    "Text my ex, huh",
    "Wife's such a nag",
    "A few beers, right?",
    "I'm drunk? How?",
    "Who made this road?",
    "Not a drunk, him",
    "Didn't learn from him",
    "No map, I'm fine",
    "Who needs sleep anyway",
    "Call brother? Nah, nah",
    "Did I leave oven?"
];

export { drunkThoughts }; 